# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(838, 592)
        Dialog.setMinimumSize(QtCore.QSize(488, 375))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(40, 100, 551, 381))
        self.listView.setObjectName("listView")
        self.Executar = QtWidgets.QPushButton(Dialog)
        self.Executar.setGeometry(QtCore.QRect(20, 500, 151, 61))
        self.Executar.setObjectName("Executar")
        self.Criar_Nome = QtWidgets.QPushButton(Dialog)
        self.Criar_Nome.setGeometry(QtCore.QRect(190, 500, 181, 61))
        self.Criar_Nome.setObjectName("Criar_Nome")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(40, 30, 551, 61))
        self.textEdit.setObjectName("textEdit")
        self.Eliminar = QtWidgets.QPushButton(Dialog)
        self.Eliminar.setGeometry(QtCore.QRect(410, 500, 151, 61))
        self.Eliminar.setObjectName("Eliminar")
        self.Total = QtWidgets.QLabel(Dialog)
        self.Total.setGeometry(QtCore.QRect(670, 150, 101, 51))
        self.Total.setObjectName("Total")
        self.Id_Seleccionado = QtWidgets.QLabel(Dialog)
        self.Id_Seleccionado.setGeometry(QtCore.QRect(630, 340, 201, 51))
        self.Id_Seleccionado.setObjectName("Id_Seleccionado")
        self.Pesquisar = QtWidgets.QPushButton(Dialog)
        self.Pesquisar.setGeometry(QtCore.QRect(590, 500, 151, 61))
        self.Pesquisar.setObjectName("Pesquisar")
        self.lcdNumber_id = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_id.setGeometry(QtCore.QRect(630, 400, 111, 51))
        self.lcdNumber_id.setObjectName("lcdNumber_id")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Executar.setText(_translate("Dialog", "Executar"))
        self.Criar_Nome.setText(_translate("Dialog", "Criar_Nome"))
        self.Eliminar.setText(_translate("Dialog", "Eliminar"))
        self.Total.setText(_translate("Dialog", "Total"))
        self.Id_Seleccionado.setText(_translate("Dialog", "Id_Seleccionado"))
        self.Pesquisar.setText(_translate("Dialog", "Pesquisar"))
