# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(695, 703)
        Dialog.setMinimumSize(QtCore.QSize(488, 375))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.btn_mult = QtWidgets.QPushButton(Dialog)
        self.btn_mult.setGeometry(QtCore.QRect(140, 270, 71, 51))
        self.btn_mult.setObjectName("btn_mult")
        self.txt_num1 = QtWidgets.QLineEdit(Dialog)
        self.txt_num1.setGeometry(QtCore.QRect(20, 30, 671, 81))
        self.txt_num1.setObjectName("txt_num1")
        self.txt_num2 = QtWidgets.QLineEdit(Dialog)
        self.txt_num2.setGeometry(QtCore.QRect(20, 150, 671, 81))
        self.txt_num2.setObjectName("txt_num2")
        self.txt_resultado = QtWidgets.QLineEdit(Dialog)
        self.txt_resultado.setGeometry(QtCore.QRect(20, 360, 661, 91))
        self.txt_resultado.setObjectName("txt_resultado")
        self.btn_div = QtWidgets.QPushButton(Dialog)
        self.btn_div.setGeometry(QtCore.QRect(230, 270, 71, 51))
        self.btn_div.setObjectName("btn_div")
        self.btn_sum = QtWidgets.QPushButton(Dialog)
        self.btn_sum.setGeometry(QtCore.QRect(330, 270, 71, 51))
        self.btn_sum.setObjectName("btn_sum")
        self.btn_sub = QtWidgets.QPushButton(Dialog)
        self.btn_sub.setGeometry(QtCore.QRect(430, 270, 71, 51))
        self.btn_sub.setObjectName("btn_sub")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_mult.setText(_translate("Dialog", "*"))
        self.btn_div.setText(_translate("Dialog", "/"))
        self.btn_sum.setText(_translate("Dialog", "+"))
        self.btn_sub.setText(_translate("Dialog", "-"))
